### ISSUE TITLE
리드미 생체인증 쪽 샘플코드 수정

### ISSUE THREAD

**Issue by youjun-lee** [tosspayments/brandpay-sdk-android-sample#2]
https://github.com/tosspayments/brandpay-sdk-android-sample/blob/a13f3aa7935e21ec03ff3b0236e222376d0efcb3/README.md?plain=1#L180C7-L180C7

ConnectPayAuthWebManager > BrandPayAuthWebManager와 같이 
Readme에서 ConnectPay를 BrandPay로 모두 수정되어야 할 것 같아요 

@JooYang

**Comment by joi0104** [comment]
https://github.com/tosspayments/brandpay-sdk-android-sample/pull/3 에서 수정되어 닫습니다.
